<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>disable</Nullable>
		<UseWindowsForms>true</UseWindowsForms>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MQTTnet" Version="5.1.0.1559" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	</ItemGroup>

	<ItemGroup>
    <Reference Include="Scm.Common.Text">
      <HintPath>..\..\Libs\netstandard2.0\Scm.Common.Text.dll</HintPath>
    </Reference>
    <Reference Include="Scm.Common.Time">
      <HintPath>..\..\Libs\netstandard2.0\Scm.Common.Time.dll</HintPath>
    </Reference>
	</ItemGroup>

</Project>